#!/bin/sh

[ -f /etc/sysconfig/clamd ] && . /etc/sysconfig/clamd

[ -z "$UPDATE_HOUR" ] && UPDATE_HOUR=2
[ -z "$UPDATE_QUIET" ] && UPDATE_QUIET="yes"

DIV="$(echo "$(LC_ALL=C date "+%H % ${UPDATE_HOUR}")" | bc)"

if [ "$UPDATE_QUIET" = "yes" ]; then
    freshclamopt="--quiet"
fi
    
if [ "$DIV" = "0" ]; then
	umask 022
	log=$(/usr/bin/freshclam $freshclamopt --daemon-notify 2>&1)
	if [ "$UPDATE_QUIET" != "yes" ]; then
	    echo "$log"
	fi
fi

