#!/bin/sh

[ -f /etc/sysconfig/clamd ] && . /etc/sysconfig/clamd
[ -n "$UPDATE_HOUR" -a "$UPDATE_HOUR" -gt 0 ] || UPDATE_HOUR=2

[ $((`date '+%k'` % $UPDATE_HOUR)) -eq 0 ] || exit 0

# sleep random period to avoid all servers hitting clamav servers at the same time,
# but 1800 seconds (half an hour) at most
sleep $((RANDOM % 1800))

[ "$UPDATE_MAIL_MESSAGES" ] || UPDATE_MAIL_MESSAGES="errors"
[ "$UPDATE_MAIL_MESSAGES" = "errors" ] && freshclamopt="--quiet"

[ -f /var/lock/subsys/clamd ] && notify="--daemon-notify" || notify=

umask 022
log=$(/usr/bin/freshclam $freshclamopt $notify 2>&1)
[ "$UPDATE_MAIL_MESSAGES" != "none" -a -n "$log" ] && echo "$log"
